### PR TITLE
Enable NOT control for filters only; use custom control DCC-4835

### PR DESCRIPTION
**Pull request by cheapsteak**
image

image

### CODE REVIEW

**Comment by btiernay** [comment]
Looks good. What do you think about the following motif instead?

screen shot 2016-06-20 at 12 49 52 pm

screen shot 2016-06-20 at 12 50 49 pm

**Comment by cheapsteak** [comment]
Good idea, implemented (it was just the font color for "not" labels, right?)

image

**Comment by btiernay** [comment]
Also using the blue link color instead of green to reduce the color palette and have consistency with the status viewer. Also makes it consistent with the approach for NOT state.

**Comment by cheapsteak** [comment]
Done

image

**Comment by cheapsteak** [comment]
Removed toggle button from the location facet

**Comment by cheapsteak** [comment]
image

Updated size, alignment, animation duration

**Pull request merged**
