### PR TITLE
Repository Browser - Add charts above hits, similar to AS #DCC-4216

### PR DESCRIPTION
**Pull request by cheapsteak**
image

Note that there's quite a few large pie portions that are "no data"

image

image

Not sure if this is an issue

### CODE REVIEW

**Comment by btiernay** [comment]
Did you mean to have 2 "Software" pies?

**Comment by cheapsteak** [comment]
image

ok fixed again, replaced space with `&nbsp;`

**Comment by cheapsteak** [comment]
charts hidden
image

charts visible
image

**Comment by btiernay** [comment]
Need to update the "units" for facets that relate to donors

**Comment by slovit** [comment]
test this please

**Comment by btiernay** [comment]
test this please

**Comment by cheapsteak** [comment]
image

Added bar chart for repositories

**Comment by btiernay** [comment]
Looks good!

But:

```app/scripts/highcharts/js/directives.js
  line 722  col 141  Line is too long.

app/scripts/repository/js/repository.js
  line 543  col 32   'e' is defined but never used.```

**Comment by btiernay** [comment]
A couple of suggestions:

- Drop the font size just enough so that `PCAWG Chicago` can be differentiated
- Move text slightly closer to axis and elide less characters (but preserve a bit of bottom padding)
- Maybe use grey instead of black for the labels?
- Maybe add one more major tick on y-axis

Keep in mind we may have 1 or 2 more repos to add soon.

**Comment by cheapsteak** [comment]
Ready for further review & feedback

image

**Comment by btiernay** [comment]
```
app/scripts/repository/js/repository.js
  line 901  col 11  Bad line breaking before '?'.
  line 915  col 6   Unnecessary semicolon.
```

**Comment by cheapsteak** [comment]
Removed warnings, implemented clicking to toggle

**Comment by cheapsteak** [comment]
Add cloud icons
image

**Comment by btiernay** [comment]
@cheapsteak  Conflicts!!!!!

**Pull request merged**
