### PR TITLE
Upgrade Angular version to 1.5.7

### PR DESCRIPTION
**Pull request by cheapsteak**
For testing on dev server

### CODE REVIEW

**Comment by btiernay** [comment]
Looks like this failed: http://dcc-jenkins1.oicr.on.ca:8080/job/dcc-portal-pr/1682/org.icgc.dcc$dcc-portal-ui/console

**Comment by btiernay** [comment]
ok to test

**Comment by cheapsteak** [comment]
That's odd, it was running fine locally

I'm pretty sure the code incompatibility warning can be ignored, most of them are asking for versions we weren't using before either

**Comment by cheapsteak** [comment]
Hmm, trying to clone from home but artifactory keeps timing me out
Does one need to be on a VPN to install and run this? Seems problematic

**Comment by btiernay** [comment]
No, should be fine. No VPN needed.

Why do you need artifactory to clone?

**Comment by cheapsteak** [comment]
Sorry I meant installing dependencies
Cloning works but I can't run it since I can't install dependencies because artifactory keeps timing me out

**Comment by btiernay** [comment]
From, https://github.com/icgc-dcc/dcc-portal/tree/develop/dcc-portal-ui did you install:

`npm install -g bower-art-resolver`

?

**Comment by cheapsteak** [comment]
Unfortunately yes

```
bower retry         Request to https://artifacts.oicr.on.ca/artifactory/api/bower/bower-dependencies/packages/angular-lodash failed with ETIMEDOUT, retrying in 17.3s
```

My internet seems to have some problem with icgc's servers, it's still unable to open the main website at dcc.icgc.org. I wonder what gives...

The bower issues are easily enough resolved by overriding the .bowerrc to have it fetch from the official sources for now, but maven can't install the api's dependencies and that I'm not sure how to override (and even if I could I guess it wouldn't be able to connect to the db due to my internet problems)

The server isn't firewalling me, is it?

**Comment by btiernay** [comment]
It could be ya, this has happened to certain users before. Can you please email it with your IP and tell them the issue?

**Comment by cheapsteak** [comment]
Still unable to reproduce locally
I've deleted my bower_components folder and installed everything from scratch, the site loads fine, clicked through pretty much everything, no errors

How does that error get triggered? (I just bugged helpdesk again about giving me access to jenkins)

**Comment by btiernay** [comment]
type `mvn` in the `dcc-portal-ui` directory

**Comment by cheapsteak** [comment]
Now running on https://dev.dcc.icgc.org/view/2

**Pull request merged**
